---
name: gpdb-demo-cluster

director_uuid: 63ddb6a6-d6fe-40e1-b16b-2ff6b2034c79

releases:
  - {name: gpdb-release-from-src, version: latest}

stemcells:
- alias: default
  os: centos-7
  version: latest

update:
    canaries: 1
    max_in_flight: 10
    canary_watch_time: 1000-30000
    update_watch_time: 1000-30000

instance_groups:
- name: master-and-segments
  instances: 1
  azs: [z1]
  jobs:
  - name: gpdb 
    release: gpdb-release-from-src
  vm_type: default
  stemcell: default
  persistent_disk_type: 10GB
  networks:
  - name: default
